### ISSUE TITLE
Copy&paste error in deprecation warning in coreunit.lua

### ISSUE THREAD

**Issue by psyK2329** [dual-universe/lua-examples#1]
https://github.com/dual-universe/lua-examples/blob/e8ff13f9720b787148f84047742b823eba87a479/api-mockup/coreunit.lua#L183

function self.getElementTypeById(localId) error("CoreUnit.**_getCycleCountSinceStartup_**(localId)...

**Comment by NQ-Ligo** [comment]
Good catch, fixed it.
