### ISSUE TITLE
core.getWorldVertical misleading

### ISSUE THREAD

**Issue by seennotheard** [dual-universe/lua-examples#17]
core.getWorldVertical actually points downwards, ie same direction as gravity. There should be documentation specifying the direction.

**Comment by NQ-Ligo** [comment]
```
    --- Returns the vertical unit vector along gravity, in world coordinates (0 in space)
    ---@return table value The local vertical vector in world coordinates in meters
    function self.getWorldVertical() end
```
    
The documentation says it's along the gravity. Is that not clear?

**Comment by seennotheard** [comment]
In the documentation, "along gravity" can generally be perceived to mean that it is colinear with the gravity vector, but it does not really specify a direction. Perhaps a better description would be "Returns the gravity unit vector, in world coordinates (0 in space)"

**Comment by NQ-Ligo** [comment]
Can be better indeed, I will replace it here and in game later.
