### ISSUE TITLE
Copy and paste error in coreunit.lua

### ISSUE THREAD

**Issue by du-git** [dual-universe/lua-examples#19]
I think there's some copy and paste error in coreunit.lua line 50, where the deprecation warning referes to a non existing function construct.getSchematic()
https://github.com/dual-universe/lua-examples/blob/ffde629b578177ae85d60903b1f91798ff1335f8/api-mockup/coreunit.lua#L50

**Comment by NQ-Ligo** [comment]
Oh thanks ! I fix it
