### ISSUE TITLE
Returns unusual values

### ISSUE THREAD

**Issue by aaronstackpole** [dual-universe/lua-examples#25]
https://github.com/dual-universe/lua-examples/blob/d9ed4cb14c83c17313ae3dcd7ce8cc5f31ed016a/api-mockup/container.lua#L37

Calling this results in a returned table that contains the values "pack remove concat unpack sort move insert" rather than ID and quantity pairs as described.

**Comment by Jericho1060** [comment]
what you are listing are the table methods in standard lua (`table.pack()`, `table.remove()`, ...)
you should try to loop on the content before displaying the keys:

```lua
local content = container.getContent()
for i, itemSlot in ipairs(content) do
     --do what you want for every items in the container
end
```
