### ISSUE TITLE
weapon.getStatus() documentation is not up to date

### ISSUE THREAD

**Issue by anatoly-kussul** [dual-universe/lua-examples#27]
Seems like actual statuses are:
```
1 - Idle
2 - Firing
3 - ?
4 - Reloading
5 - Unloading
6 - Fire Blocked
```

https://github.com/dual-universe/lua-examples/blob/d9ed4cb14c83c17313ae3dcd7ce8cc5f31ed016a/api-mockup/weapon.lua#L70-L72

**Comment by NQ-Ligo** [comment]
Indeed, I checked, it's :
```
Idle = 1,
Firing = 2,
Stopping = 3,
Reloading = 4,
Unloading = 5,
FiringBlocked = 6
```

I will update the documentation and the ingame CODEX
